name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Compile Multi-Architecture
        run: |
          go mod tidy
          # Build untuk PC (AMD64)
          GOOS=linux GOARCH=amd64 go build -o bvm-amd64 ./cmd/bvm
          # Build untuk HP/Termux (ARM64)
          GOOS=linux GOARCH=arm64 go build -o bvm-arm64 ./cmd/bvm

          # Bungkus keduanya dalam satu ZIP
          zip bvm-releases.zip bvm-amd64 bvm-arm64

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: bvm-releases.zip # Pastikan nama file ini sama dengan hasil zip di atas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
